### ISSUE TITLE
Crash on startup on certain devices.

### ISSUE THREAD

**Issue by val-pu** [val-mx/TheGameOfLife#1]
FATAL EXCEPTION: main
                                                                                                    Process: leko.valmx.thegameoflife, PID: 11877
                                                                                                    java.lang.IllegalArgumentException: bound must be positive
                                                                                                    	at java.util.Random.nextInt(Random.java:388)
                                                                                                    	at leko.valmx.thegameoflife.MainActivity.onCreate$lambda-2(MainActivity.kt:98)
                                                                                                    	at leko.valmx.thegameoflife.MainActivity.$r8$lambda$im0Qteczjk92lm9-Q0QO9vwFRpE(Unknown Source:0)
                                                                                                    	at leko.valmx.thegameoflife.MainActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:808)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loop(Looper.java:166)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by val-pu** [comment]
fixed.
